services:
  frontend:
    build: ./client
    ports:
      - "0.0.0.0:8443:8443"
    depends_on:
      - backend

  backend:
    build: ./server
    expose:
      - "3001"
    environment:
    - NODE_ENV=development
    - DATABASE_PATH=/app/database/data/database.db
    - HOST_LAN_IP=${HOST_LAN_IP}

    volumes:
      - ./server/database/data:/app/database/data
      - ./server/database/uploads:/app/database/uploads
