services:
  frontend:
    build: ./src
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./src/backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/database/data/database.db
    volumes:
      - ./src/backend/database/data:/app/database/data
      - ./src/backend/database/uploads:/app/database/uploads
